M48
; DRILL file {KiCad 9.0.1} date 2025-04-18T13:59:54+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-18T13:59:54+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.350
%
G90
G05
T1
X34.81Y40.945
X40.59Y40.945
T2
X6.15Y33.5
X12.15Y33.5
T3
X15.0Y41.1
X15.0Y9.1
X55.0Y41.1
X55.0Y9.1
T4
X9.0Y25.78
X9.0Y15.62
M30
